package com.emutune.data.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entities use primitive IDs rather than the domain value classes. Mapping to and
 * from the domain happens in [Mappers], keeping persistence concerns out of the domain
 * model.
 *
 * Autogenerated-key entities default their id to 0 so Room assigns a fresh id on insert
 * while still honouring explicit nonzero ids (used by the debug seeder).
 */

@Entity(tableName = "games")
data class GameEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val sortKey: String,
    val createdAt: Long,
)

@Entity(tableName = "game_editions")
data class GameEditionEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val gameId: Long,
    val platformId: String,
    val name: String,
    val region: String?,
    val platformIdentifier: String?,
)

@Entity(tableName = "execution_routes")
data class ExecutionRouteEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val gameEditionId: Long,
    val platformId: String,
    val emulatorId: String,
    val emulatorBuildId: String?,
    val gpuDriverId: String?,
    val translationLayerId: String?,
    val configurationId: Long?,
)

@Entity(tableName = "observations")
data class ObservationEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val gameEditionId: Long,
    val executionRouteId: Long,
    val deviceFingerprintId: Long,
    val metricsJson: String,
    val durationSeconds: Int?,
    val benchmarkMethod: String,
    val evidenceGrade: String,
    val success: Boolean,
    val crashCount: Int,
    val recordedAt: Long,
    val providerId: String?,
)

@Entity(tableName = "device_profile")
data class DeviceProfileEntity(
    @PrimaryKey val id: Long = 1,
    val fingerprintJson: String,
)

@Entity(tableName = "emulator_installations", primaryKeys = ["emulatorId", "packageId"])
data class EmulatorInstallationEntity(
    val emulatorId: String,
    val packageId: String,
    val versionName: String?,
    val versionCode: Long?,
    val detectedAt: Long,
)

/** The single current play session (one row, keyed at 1 like [DeviceProfileEntity]). */
@Entity(tableName = "play_session")
data class PlaySessionEntity(
    @PrimaryKey val id: Long = 1,
    val gameEditionId: Long,
    val routeId: Long?,
    val source: String,
    val startedAt: Long,
)

@Entity(tableName = "activity_events")
data class ActivityEventEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val type: String,
    val title: String,
    val detail: String?,
    val gameId: Long?,
    val occurredAt: Long,
)
